// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _BaseLayout = "_BaseLayout";
                public readonly string _Layout = "_Layout";
            }
            public readonly string _BaseLayout = "~/Views/Shared/_BaseLayout.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string CanonicalHelperModel = "CanonicalHelperModel";
                public readonly string Check = "Check";
                public readonly string ImageUrl = "ImageUrl";
                public readonly string MenuHelperModel = "MenuHelperModel";
                public readonly string MetaRobotsHelperModel = "MetaRobotsHelperModel";
                public readonly string SBAdmin2MenuHelperModel = "SBAdmin2MenuHelperModel";
                public readonly string SBAdmin2SiteMapNodeModel = "SBAdmin2SiteMapNodeModel";
                public readonly string SBAdmin2SiteMapNodeModelList = "SBAdmin2SiteMapNodeModelList";
                public readonly string SiteMapHelperModel = "SiteMapHelperModel";
                public readonly string SiteMapNodeModel = "SiteMapNodeModel";
                public readonly string SiteMapNodeModelList = "SiteMapNodeModelList";
                public readonly string SiteMapPathHelperModel = "SiteMapPathHelperModel";
                public readonly string SiteMapTitleHelperModel = "SiteMapTitleHelperModel";
                public readonly string Time = "Time";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Boolean = "Boolean";
                public readonly string Date = "Date";
                public readonly string DateTime = "DateTime";
                public readonly string EmailAddress = "EmailAddress";
                public readonly string Enum = "Enum";
                public readonly string Html = "Html";
                public readonly string ImageUrl = "ImageUrl";
                public readonly string List = "List";
                public readonly string MultilineText = "MultilineText";
                public readonly string MultiSelectList = "MultiSelectList";
                public readonly string Password = "Password";
                public readonly string Text = "Text";
                public readonly string Time = "Time";
                public readonly string Upload = "Upload";
            }
            static readonly _LayoutPageClass s_LayoutPage = new _LayoutPageClass();
            public _LayoutPageClass LayoutPage { get { return s_LayoutPage; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _LayoutPageClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Head = "Head";
                    public readonly string NavbarHeader = "NavbarHeader";
                    public readonly string NavbarTopLink = "NavbarTopLink";
                    public readonly string Sidebar = "Sidebar";
                }
                public readonly string Head = "~/Views/Shared/LayoutPage/Head.cshtml";
                public readonly string NavbarHeader = "~/Views/Shared/LayoutPage/NavbarHeader.cshtml";
                public readonly string NavbarTopLink = "~/Views/Shared/LayoutPage/NavbarTopLink.cshtml";
                public readonly string Sidebar = "~/Views/Shared/LayoutPage/Sidebar.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
